### ISSUE TITLE
Fix geo location

### ISSUE THREAD

**Issue by vansteph** [ubvu/2023-09-25-uvavu#3]
geo location has to be changed to correct address: Roeterseiland Campus, Roetersstraat 15-27

Monday 25th of September, 09.30 – 14.30 CEST               room REC B2.08, Roeterseiland Campus, Roetersstraat 15-27
Tuesday 26th of September, 09.30 – 14.30 CEST               room REC E0.03, Roeterseiland Campus, Roetersstraat 15-27
Wednesday 27th of September, 09.30 – 14:30 CEST        room REC E0.03, Roeterseiland Campus, Roetersstraat 15-27
Thursday 28th of September, 09.30 – 14:30 CEST             room REC E0.15, Roeterseiland Campus, Roetersstraat 15-27

**Comment by wmotion** [comment]
Done with commits e46c3025d490e1696b5545f80c61f09af815460e and f7fc90747e2417805454e3e302665d9f7f45e385.
